universe = vanilla

request_cpus = 1
request_memory = 120GB
request_disk = 800GB

# Extra GPU settings
request_gpus            = 1

# change to true if *not* using staging for checkpoints and interested in accessing GPUs beyond CHTC
+WantGPULab = true
+WantFlocking           = false
+WantGlidein            = false
+GPUJobLength           = "short"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (Target.HasCHTCStaging == true) && (Target.CUDADriverVersion >= 12.1) && (Target.GPUs_GlobalMemoryMb > 40960)

+InteractiveJob = true


queue 1
